name: Deploy to AWS Lambda

# Esegui l'azione quando fai push sul branch "main"
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout del codice dalla tua repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Installazione di Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    # Installazione delle dipendenze
    - name: Install dependencies
      run: npm install

    # Zippa il codice
    - name: Zip code
      run: zip -r function.zip .

    # Carica la funzione Lambda su AWS
    - name: Deploy to AWS Lambda
      # Usa awscli per aggiornare la funzione Lambda
      run: |
        aws lambda update-function-code --function-name messaging-webhook --zip-file fileb://function.zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1' # La tua regione AWS
